FROM ubuntu:latest
LABEL maintainer="adeelarifbhatti@gmail.com"
WORKDIR /app
RUN apt-get update && apt-get install -y openjdk-8-jdk
COPY src/Client Client
COPY src/CountryCapital.idl CountryCapital.idl
COPY start-client.sh ./
RUN idlj -fall CountryCapital.idl
RUN javac CountryCapital/*.java
RUN javac  Client/*.java
# EXPOSE 8080 900
RUN chmod +x ./start-client.sh
ENTRYPOINT ["sh","-c","./start-client.sh && sleep infinity"]
