version: "2.0"
services:

 graphcore-server:
  build:
   context: .
   dockerfile: Dockerfile
  ports:
   -  "900:900"
   
 graphcore-api:
  build:
   context: .
   dockerfile: Dockerfile-api
  ports:
   -  "80:8080"
